version: '3.8'
services:
  frontend:
    container_name: campushub-frontend
    image: aslambaba/campushub:frontend
    build: ./frontend/
    ports:
      - "3000:80"
    depends_on:
      - backend
  backend:
    container_name: campushub-backend
    image: aslambaba/campushub:backend
    build: ./backend/
    ports:
      - "8000:8000"
    depends_on:
      - redis
  redis:
    container_name: campushub-redis-cache
    image: redis
    ports:
      - "6379:6379"